apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tf-app 
  namespace: flux-system 
spec:
  interval: 1m0s
  ref:
    branch: main 
  url: https://github.com/inemyrovsk/terraform-cd-with-flux
