apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: tf-app
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  path: ./infrastructure
  destroyResourcesOnDeletion: true
  sourceRef:
    kind: GitRepository
    name: tf-app
    namespace: flux-system
  writeOutputsToSecret:
    name: tf-app-output
      - http_ip
      - db_ip
  runnerPodTemplate:
    spec:
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_REGION
